[package]
name = "print-jobber"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["tokio"] }
escpos = { version = "0.17.0", features = ["usb"] }
tokio = { version = "1.49.0", features = ["rt-multi-thread"] }
